# Generated by Django 4.2.17 on 2024-12-25 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MutualFundFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MutualFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_code', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('scheme_name', models.CharField(blank=True, max_length=100, null=True)),
                ('net_asset_value', models.PositiveIntegerField(default=0, verbose_name='NAV')),
                ('last_updated_datetime', models.DateTimeField(auto_now=True)),
                ('scheme_type', models.CharField(blank=True, max_length=25, null=True)),
                ('scheme_category', models.CharField(blank=True, max_length=100, null=True)),
                ('fund_family', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mutual_fund.mutualfundfamily')),
            ],
        ),
    ]
