# Generated by Django 4.2.17 on 2024-12-26 05:33

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appuser',
            managers=[
                ('objects', users.models.AppUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='userinvestdetails',
            name='amount_invested',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
